GLOBAL.setmetatable(env,{__index=function(t,k) return GLOBAL.rawget(GLOBAL,k) end})

PrefabFiles = {
	"abby",
	"abby_flower",
	"abigail_attack_fx",
	"abigailforcefield",
	"wendst",
}

Assets = {
	Asset( "IMAGE", "images/saveslot_portraits/wendst.tex"),
	Asset( "ATLAS", "images/saveslot_portraits/wendst.xml"),
	Asset( "IMAGE", "images/selectscreen_portraits/wendst.tex"),
	Asset( "ATLAS", "images/selectscreen_portraits/wendst.xml"),
	Asset( "IMAGE", "images/selectscreen_portraits/wendst.tex"),
	Asset( "ATLAS", "images/selectscreen_portraits/wendst_silho.xml"),	
	Asset( "IMAGE", "bigportraits/wendst.tex"),
	Asset( "ATLAS", "bigportraits/wendst.xml"),	
	Asset( "IMAGE", "minimap/wendst.tex"),
	Asset( "ATLAS", "minimap/wendst.xml"),
	Asset("ANIM", "anim/abigail_attack_fx.zip"),
	Asset("ANIM", "anim/abigail_buff_drip.zip"),
	Asset("ANIM", "anim/abigail_debuff_fx.zip"),
	Asset("ANIM", "anim/abigail_flower_change.zip"),
	Asset("ANIM", "anim/abigail_flower_rework.zip"),
	Asset("ANIM", "anim/abigail_shield.zip"),
	Asset("ANIM", "anim/abigail_vial_fx.zip"),
	Asset("ANIM", "anim/ghost_abigail.zip"),
	Asset("ANIM", "anim/ghost_abigail_build.zip"),
	Asset("ANIM", "anim/player_ghost_withhat.zip"),
	Asset("ANIM", "anim/player_idles_wendy.zip"),
	Asset("ANIM", "anim/player_wendy_commune.zip"),
	Asset("ANIM", "anim/player_wendy_mount_commune.zip"),
	Asset("ANIM", "anim/wendst.zip"),
	Asset("ANIM", "anim/wendy_channel.zip"),
	Asset("ANIM", "anim/wendy_channel_flower.zip"),
	Asset("ANIM", "anim/wendy_mount_channel.zip"),
	Asset("ANIM", "anim/wendy_mount_channel_flower.zip"),
	Asset("ANIM", "anim/wendy_mount_recall.zip"),
	Asset("ANIM", "anim/wendy_mount_recall_flower.zip"),
	Asset("ANIM", "anim/wendy_recall.zip"),
	Asset("ANIM", "anim/wendy_recall_flower.zip"),
}